plugin_paths:
  - 'lib/plugin/cache'
  - 'lib/plugin/storage'

storage:
  id:     'rdf-storage'
  plugin: 'redland'
  options:
    storage:     'sqlite'
    name:        'rdf.db'
    synchronous: 'off'

cache:
  id:     'namespace-cache'
  plugin: 'kyotocabinet'
  name:   'file-cache'
  options:
    type:  'file-hash'
    file:  '/tmp/namespace-db.kch'
    mode:
      - 'writer'
      - 'create'

namespace:
  storage: 'rdf-storage'
  cache:   'namespace-cache'
# vim: ts=2 sts=2 sw=2
# encoding: utf-8
