plugin_paths:
  - 'lib/plugin/annotation'
  - 'lib/plugin/cache'
  - 'lib/plugin/evidence'
  - 'lib/plugin/namespace'
  - 'lib/plugin/search'
  - 'lib/plugin/storage'

evidence-api:
  type:   'evidence'
  plugin: 'evidence'
  options:
    host:     'localhost'
    port:     27017
    database: 'openbel'


# vim: ts=2 sts=2 sw=2
# encoding: utf-8
