plugin_paths:
  - 'lib/plugin/cache'
  - 'lib/plugin/namespace'
  - 'lib/plugin/storage'

namespace-cache:
  type:   'cache'
  plugin: 'kyotocabinet'

  options:
    type: 'file-hash'
    file: '/tmp/namespace-db.kch'
    mode:
      - 'writer'
      - 'create'

namespace-storage:
  type:   'storage'
  plugin: 'redland'

  options:
    storage:     'sqlite'
    name:        'rdf.db'
    new:         'no'
    synchronous: 'no'

namespace-api:
  type:   'namespace'
  plugin: 'namespace'
  extensions:
    storage: 'namespace-storage'
    # cache:   'namespace-cache'

# vim: ts=2 sts=2 sw=2
# encoding: utf-8
