plugin_paths:
  - 'lib/plugin/annotation'
  - 'lib/plugin/cache'
  - 'lib/plugin/evidence'
  - 'lib/plugin/namespace'
  - 'lib/plugin/search'
  - 'lib/plugin/storage'

rdf-cache:
  type:   'cache'
  plugin: 'kyotocabinet'
  options:
    type: 'file-hash'
    mode:
      - 'writer'
      - 'create'

rdf-storage:
  type:   'storage'
  plugin: 'redland'
  extensions:
    cache: 'rdf-cache'
  options:
    storage:     'sqlite'
    name:        'rdf_20150611.db'
    new:         'no'
    synchronous: 'no'

rdf-search:
  type:   'search'
  plugin: 'sqlite3_search'
  options:
    file: 'rdf_20150611.db'

annotation-api:
  type:   'annotation'
  plugin: 'annotation'
  extensions:
    storage: 'rdf-storage'
    search:  'rdf-search'

namespace-api:
  type:   'namespace'
  plugin: 'namespace'
  extensions:
    storage: 'rdf-storage'
    search:  'rdf-search'

evidence-api:
  type:   'evidence'
  plugin: 'evidence'
  options:
    host:     'localhost'
    port:     27017
    database: 'openbel'


# vim: ts=2 sts=2 sw=2
# encoding: utf-8
