plugin_paths:
  - 'lib/plugin/cache'
  - 'lib/plugin/evidence'
  - 'lib/plugin/namespace'
  - 'lib/plugin/storage'

namespace-cache:
  type:   'cache'
  plugin: 'kyotocabinet'
  options:
    type: 'file-hash'
    mode:
      - 'writer'
      - 'create'

namespace-storage:
  type:   'storage'
  plugin: 'redland'
  extensions:
    cache: 'namespace-cache'
  options:
    storage:     'sqlite'
    name:        'rdf.db'
    new:         'no'
    synchronous: 'no'

namespace-api:
  type:   'namespace'
  plugin: 'namespace'
  extensions:
    storage: 'namespace-storage'

evidence-api:
  type:   'evidence'
  plugin: 'evidence'
  options:
    host:     'localhost'
    port:     27017
    database: 'openbel'

# vim: ts=2 sts=2 sw=2
# encoding: utf-8
