version: '2'

volumes:
  mongodb_data: {}
  resource_search: {}
  rdf_store: {}

services:
  mongodb:
    image: mongodb:3.4
  jruby:
    build:
        context: ./dir
        dockerfile: Dockerfile-alternate




