version: '2'

volumes:
  mongodb_data:

services:

  mongodb:
    image: mongo:3.2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  api:
    build:
      context: ./containers/api
    depends_on:
      - mongodb
    environment:
      OPENBEL_API_CONFIG_FILE: /config/config.yml
    expose:
      - "9292"
    ports:
      - "9292:9292"
    volumes:
      - .:/app
      - ./config:/config
      - ./data:/data
    restart: always
