version: '2'

volumes:
  mongodb_data: {}

services:
  mongodb:
    image: mongo:3.2
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  api:
    build:
        context: ./containers/api
        dockerfile: Dockerfile-prod
    depends_on:
      - mongodb
    environment:
      OPENBEL_API_CONFIG_FILE: /config/config.yml
      RACK_ENV: production
    expose:
     - "9292"
    ports:
      - "9292:9292"
    volumes:
      - "./data:/data"
      - "./config/config.yml:/config/config.yml"
    restart: always
