source 'https://rubygems.org'

gem 'bel', :git => 'git@github.com:OpenBEL/bel.rb.git'
gem 'builder'
gem 'dot_hash'
gem 'nokogiri'
gem 'oj'
gem 'roar'
gem 'sinatra'
gem 'sinatra-advanced-routes', :require => 'sinatra/advanced_routes'
gem 'sinatra-contrib'
gem 'sinatra-docdsl'

group :development do
  gem 'bond'
  gem 'jist'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-docmore'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'perftools.rb'
  gem 'rack-perftools_profiler'
  gem 'rerun'
  gem 'term-ansicolor'
  gem 'thin'
  gem 'yard'
end
# vim: ts=2 sw=2
