#%RAML 0.8
title: OpenBEL API
version: 0.0.2
baseUri: http://localhost:3000
/api:
  /expressions/{bel}/completions:
    uriParameters:
      bel:
        type: string
        description: BEL statement; Completions will be provided for this input.
        required: false
    get:
      headers:
        Accept:
          displayName: Accept
      queryParameters:
        caret_position:
          type: integer
          description: The position of the caret within the *bel* input. Defaults to the right-most caret_position for *bel* (e.g. length of *bel* input).
          example: 0
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "completion": {
                      "type": "namespace_prefix",
                      "label": "HGNC",
                      "value": "HGNC:",
                      "highlight": {
                        "start_position": 2,
                        "end_position": 3,
                        "range_type": "inclusive"
                      },
                      "actions": [
                        {
                          "delete": {
                              "start_position": 2,
                              "end_position": 3,
                              "range_type": "inclusive"
                          },
                          "insert": {
                              "position": 2,
                              "value": "HGNC:"
                          },
                          "move_cursor": {
                              "position": 7
                          }
                        }
                      ]
                    }
                  }
                ]
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "completion"
                    ],
                    "additionalProperties": false,
                    "properties": {
                      "completion": {
                        "type": "object",
                        "required": [
                          "type",
                          "label",
                          "value",
                          "highlight",
                          "actions"
                        ],
                        "additionalProperties": false,
                        "properties": {
                          "type": {
                            "enum": [
                              "function",
                              "namespace_prefix",
                              "namespace_value"
                            ]
                          },
                          "label": {
                            "type": "string"
                          },
                          "value": {
                            "type": "string"
                          },
                          "highlight": {
                            "oneOf": [
                              {
                                "type": "null"
                              },
                              {
                                "type": "object",
                                "required": [
                                  "start_position",
                                  "end_position",
                                  "range_type"
                                ],
                                "properties": {
                                  "start_position": {
                                    "type": "integer"
                                  },
                                  "end_position": {
                                    "type": "integer"
                                  },
                                  "range_type": {
                                    "enum": [
                                      "exclusive",
                                      "inclusive"
                                    ]
                                  }
                                }
                              }
                            ]
                          },
                          "actions": {
                            "type": "array",
                            "items": {
                              "oneOf": [
                                {
                                  "type": "object",
                                  "required": [
                                    "delete"
                                  ],
                                  "properties": {
                                    "delete": {
                                      "type": "object",
                                      "required": [
                                        "start_position",
                                        "end_position",
                                        "range_type"
                                      ],
                                      "properties": {
                                        "start_position": {
                                          "type": "integer"
                                        },
                                        "end_position": {
                                          "type": "integer"
                                        },
                                        "range_type": {
                                          "enum": [
                                            "exclusive",
                                            "inclusive"
                                          ]
                                        }
                                      }
                                    }
                                  }
                                },
                                {
                                  "type": "object",
                                  "required": [
                                    "insert"
                                  ],
                                  "properties": {
                                    "insert": {
                                      "type": "object",
                                      "required": [
                                        "position",
                                        "value"
                                      ],
                                      "properties": {
                                        "position": {
                                          "type": "integer"
                                        },
                                        "value": {
                                          "type": "string"
                                        }
                                      }
                                    }
                                  }
                                },
                                {
                                  "type": "object",
                                  "required": [
                                    "move_cursor"
                                  ],
                                  "properties": {
                                    "move_cursor": {
                                      "type": "object",
                                      "required": [
                                        "position"
                                      ],
                                      "properties": {
                                        "position": {
                                          "type": "integer"
                                        }
                                      }
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                }
