source 'https://rubygems.org'

gem 'bel'
gem 'rdf'
gem 'json'
gem 'builder'
gem 'nokogiri'
gem 'redlander'
gem 'roar'
gem 'sinatra'

group :development do
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-nav'
  gem 'sinatra-contrib'
  gem 'perftools.rb'
  gem 'rack-perftools_profiler'
end
# vim: ts=2 sw=2
