source 'https://rubygems.org'

gem 'bel',        '~> 0.3'
gem 'daemons',    '~> 1.2'
gem 'hermann',    '0.24.1.dev'
gem 'multi_json', '~> 1'
gem 'oj',         '~> 2.12'
gem 'redlander',
  :github => 'abargnesi/redlander',
  :branch => 'rubies_support'
gem 'sqlite3'

group :development do
  gem 'pry'
end
