FROM jruby:9.1.5.0

# the container will expose 9292
# must run with port binding: -p 9292:9292
EXPOSE 9292

# need make for native extensions (even though JRuby doesn't support it)
RUN apt-get -y update && apt-get install -y make

# install latest release plus deps
RUN gem install openbel-api

# setup path for data volumes
# - /data/rdf_resources/ to hold sqlite db (biological-concepts-rdf.db)
# - /data/rdf_store/ to hold rdf store

RUN ["mkdir", "-p", "/data/rdf_resources"]
RUN ["mkdir", "-p", "/data/rdf_store"]
RUN ["mkdir", "-p", "/config"]

# copy over api config file (docker-specific) -- context is ./containers/api
# COPY ../../config/config.yml /config/config.yml

# run openbel api using docker app config
CMD ["openbel-api", "--file", "/config/config.yml"]
# vim: ft=dockerfile
