#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/../
cd "${DIR}" || exit 1

if [ -f .env ]; then
    source .env
fi

RIPPER_CTAGS=$(hash ripper-tags > /dev/null 2>&1)
if [ "$?" == "0" ]; then
    ripper-tags -R --all-files --exclude "$CTAG_EXCLUDES"
    exit $?
fi
